# fly.toml app configuration file generated for weifinder-indexer-mainnet on 2026-01-06T18:43:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weifinder-indexer-mainnet'
primary_region = 'nrt'

[build]

[env]
    RUST_LOG = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9000
  path = '/metrics'

[mounts]
  source = "indexer_volume_mainnet"
  destination = "/tmp"
