# fly.toml app configuration file generated for weifinder-indexer-mainnet on 2026-01-07T07:54:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weifinder-indexer-mainnet'
primary_region = 'nrt'

[build]

[env]
  RUST_LOG = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpus = 2
  memory_mb = 4096

[[metrics]]
  port = 9000
  path = '/metrics'

[mounts]
  source = 'local_data_mainnet'
  destination = '/data'
